### ISSUE TITLE
Masternode list

### ISSUE THREAD

**Issue by Ruxiol** [team-exor/eiquidus#6] opened 2021-05-01 13:32 UTC
Hello, first i want to thank you for such a great explorer code.

Our community forked and we are learning core basics on our community project.

As explorer is operational, it can show masternodes count, but it cannot show masternode list.

I edited rpc command that suits our coin, as it is "masternode list"

and it return like this from daemon

 "a37cf00ba91169f7255c586fecdfcfd5864e928cfdc02293c78a3a93ab49dfb9-1": {
    "proTxHash": "b68873007e51424aaff99c8bebf0b44cfe8a9ff0f3fb3c92cee5d73a917a7fff",
    "address": "161.35.16.51:23506",
    "payee": "RRWunLwWsx19FqhWoDHxgfkXKCAQwZsMf2",
    "status": "ENABLED",
    "lastpaidtime": 1619832967,
    "lastpaidblock": 55728,
    "owneraddress": "RPQGRDFU994MHAjk9xNfyKN1ZZtp4HLddn",
    "votingaddress": "RUUsqu2o2hJmKApEGUVWFxX7dBEbeRddHC",
    "collateraladdress": "RCFT8EDcHKddnwJzhdThjKshr4FRg7xskM",
    "pubkeyoperator": "846ff01786639b32faec708ece0380e1cf9ac9c63cf05f6697c17104eaadadacbf55af867b71860ed8a6e8556eb129ea"
  },

Can you point us what could be the problem that Masternode link wont show masternodes?

explorer is on https://rxcinfo.crypto.ba

Thank you!

**Comment by joeuhren** [comment] 2021-05-01 21:28
Hey, I took a quick peek at the RXC code and the problem is that the explorer is currently modelled after how DASH and PIVX masternodes work, but your masternode list output is quite different. For example, the explorer is expecting output like this:

```
  {
    "rank": 128,
    "network": "ipv6",
    "txhash": "062540b5786a1cf334bde20fef17cb2caa5fdeb9d66f974a2780c781797df8a2",
    "outidx": 0,
    "status": "ENABLED",
    "addr": "EJTyK7RFrFR6UB3WRBv55byna6bJhEm3S9",
    "version": 70914,
    "lastseen": 1619893410,
    "activetime": 4713775,
    "lastpaid": 1619884067
  }
```

but instead your coin is showing:

```
  '631949a7c5903e729df41b99a29aa44de715c5da00ec715d751624d34d45807c-1': {
    proTxHash: '4b87dc2d413d1b346b9fe9909b9b913b1f90b8f5185204ca80b18b9aa187779a',
    address: '178.62.59.111:23506',
    payee: 'RGm7rWA1TKacVnfsbu7WfvXbdv5y4xxrb2',
    status: 'ENABLED',
    lastpaidtime: 1601882164,
    lastpaidblock: 2937,
    owneraddress: 'RP2cMFzqpaBR88Ej6R1o5ZbN8HK9mU3EhC',
    votingaddress: 'RQMyQGQiKDxKfivrQSCv66p6FFWrcZUPFX',
    collateraladdress: 'RWnuQ9bRY9GKWT1ydFyjMLRsXTYaA5k2Ax',
    pubkeyoperator: '954364d89102f2498e431879a913f0891fd38aabca802c6eb3a45d4816ac232c96bb2fca83972365e4106c1f49759f94'
  }
```

The following DASH/PIVX fields will need to be mapped to what I think are the RXC equivalents:
```
lastpaid = lastpaidtime
addr = payee
txhash = proTxHash
```

But theres a ton of fields from DASH/PIVX that are not found in RXC's masternode list (there is no way to do this via config, it would have to be done by manually editing the explorer code for now):
```
activetime = ???
lastseen = ???
version = ???
outidx = ???
network = ???
rank = ???
```

RXC's masternode list also has some additional fields not found in the DASH/PIVX implemenation which could be useful to display such as the `address` or `lastpaidblock` fields for example.

Unfortunately, because of the huge differences in the data returned from the masternode list cmd, this isn't a quick or easy fix. I would like to further expand the ability for the explorer to handle these types of customizations properly, but its not very high on my priority list right now and probably won't get around to it until after v2.0 is released.

To help determine the best path forward for fixing this problem in a future update, do you know which coin RXC was cloned from? I'm mostly wondering if this newer masternode implementation was inherited from an older coin or if it was custom developed for RXC specifically?

**Comment by Ruxiol** [comment] 2021-05-01 22:56
Thank you for reply, as RXC is fork of DASH v14, with some Bitcoin properties,  so its hybrid of a newer DASH code.

Al those older DASH forks used older codes, v7-v9 thats why RXC masternode commands are different :)

As im learning, i will give my best to figure out what you suggested and if you have any time i would gladly pay you some RXC bounty :)

**Comment by joeuhren** [comment] 2021-05-03 18:31
Thanks for the info. You are correct, I can confirm that we were behind on the latest Dash masternode format and were only supporting the older format which PIVX and many other coins still use. I've now added preliminary support for the newer Dash masternode format where it will auto detect which format your data is and adjust accordingly. Stop your explorer, do a `git pull`, and then restart the explorer to take advantage of the update. The masternode data should appear after the new update is in place and after running `/path/to/explorer/scripts/sync.sh /path/to/node masternodes`.

Please take a look and let me know if you notice any problems or see anything you feel can be improved. The one thing I was not 100% sure about was which wallet address to display. The older Dash format only returned a single wallet address, but the newer format returns four wallet addresses. I opted for displaying the `payee` address, but perhaps one of the other addresses would be more correct to display instead?

**Comment by Ruxiol** [comment] 2021-05-04 14:53
Ok i did PULL, but still does not show on masternodes tab, you can check also

https://rxcinfo.crypto.ba

**Comment by joeuhren** [comment] 2021-05-05 02:26
Sorry about that, I was trying to patch this quick and therefore didn't test as thoroughly as I should have. I posted another small update which should now allow duplicate masternode wallet addresses. You will need to wipe your explorers masternode database for this to work, so that it can be recreated with the newer changes. Follow these steps:

1. #Stop the explorer
2. git pull
3. mongo
4. use explorerdb
5. db.masternodes.drop()
6. exit
7. #Restart the explorer
8. /path/to/explorer/scripts/sync.sh /path/to/node masternodes

Hopefully that should work better this time.

**Comment by Ruxiol** [comment] 2021-05-05 06:04
:) i really cannot thank you enough for this fix!

syncing masternodes.. please wait..
masternode sync complete

Please if you have time register at our wallet/mainwebsite and give me your RXC address.

Please visit https://rxc.crypto.ba

**Comment by joeuhren** [comment] 2021-05-05 15:02
You're welcome! Thanks for bringing the issue to my attention.

I wasn't really working for bounty, but if you feel inclined to send coins, I installed an RXC daemon to test this change so I have an address already: RDMv6tP1cA2ts8UugaBiBp8se8nM4kXLCp

I'm closing this issue for now, but feel free to reopen if you notice further problems later.

**Closed by joeuhren** 2021-05-05 15:02 UTC
